# Generated by Django 6.0.3 on 2026-03-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100, verbose_name='Emri i Kategorisë')),
                ('slug', models.SlugField(blank=True, help_text='Gjenerohet automatikisht', unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoritë',
            },
        ),
        migrations.CreateModel(
            name='Produkti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=200, verbose_name='Emri i Produktit')),
                ('pershkrimi', models.TextField(blank=True, verbose_name='Përshkrimi')),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Çmimi (€)')),
                ('imazhi', models.ImageField(upload_to='produktet/', verbose_name='Foto e Produktit')),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
                ('eshte_aktiv', models.BooleanField(default=True, verbose_name='I disponueshëm')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktet', to='mobileriApp.kategoria', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produktet',
                'ordering': ['-data_krijimit'],
            },
        ),
    ]
