# Generated by Django 6.0.3 on 2026-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileriApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkti',
            name='cmimi',
            field=models.CharField(max_length=50, verbose_name='Çmimi ose Statusi'),
        ),
    ]
