# Generated by Django 6.0.3 on 2026-03-30 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileriApp', '0002_alter_produkti_cmimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imazhi', models.ImageField(upload_to='produktet/galeria/')),
                ('produkti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='mobileriApp.produkti')),
            ],
            options={
                'verbose_name': 'Foto Galerie',
                'verbose_name_plural': 'Galeria e Fotove',
            },
        ),
    ]
