# Generated by Django 6.0.3 on 2026-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileriApp', '0003_fotot'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkti',
            name='shenim_shkurter',
            field=models.CharField(blank=True, max_length=255, verbose_name='Shënim i shkurtër'),
        ),
        migrations.AlterField(
            model_name='fotot',
            name='imazhi',
            field=models.ImageField(upload_to='produktet/galeria/', verbose_name='Imazhi i Galerisë'),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='imazhi',
            field=models.ImageField(upload_to='produktet/', verbose_name='Foto Kryesore'),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='pershkrimi',
            field=models.TextField(blank=True, verbose_name='Përshkrimi i detajuar'),
        ),
    ]
